pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/<christianobi1>/cloudshift-automation-toolkit.git'
            }
        }
    }
}
